language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "4"
env:
  - REACT_VERSION=0.13
  - REACT_VERSION=0.14
  - REACT_VERSION=15
  - REACT_VERSION=16
before_script:
  - ./install-dependencies.sh || echo "ignoring errors during setup"
script:
  - npm run travisci
